env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 13
  sourceType: module
plugins:
  - react
rules: {
  "no-param-reassign": 0,
  "max-len": ["error", { "code": 120 }],
  "react/prop-types": "off"
}
